name: build mdbook

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup self update
    - run: rustup default stable
    - run: rustup update
    - run: cargo install mdbook --vers  0.4.25
    - run: cargo -V
    - run: rustc -V
    - run: mdbook -V
    - run: mdbook test
    - run: mdbook build --dest-dir docs
    - run: cargo run --bin lfp src
